/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/template copy.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NChe: typeof import('naive-ui')['NChe']
    NCheck: typeof import('naive-ui')['NCheck']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NInput: typeof import('naive-ui')['NInput']
    NInputButton: typeof import('naive-ui')['NInputButton']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputGroupLabel: typeof import('naive-ui')['NInputGroupLabel']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    Package: typeof import('./src/components/Package.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    PostPackage: typeof import('./src/components/PostPackage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scan: typeof import('./src/components/Scan.vue')['default']
    Scanner: typeof import('./src/components/Scanner.vue')['default']
    Template: typeof import('./src/components/template.vue')['default']
    Transfer: typeof import('./src/components/Transfer.vue')['default']
    View: typeof import('./src/components/View.vue')['default']
  }
}
